# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  

# Text to speech
tts:
  - platform: google_cloud
    key_file: service_account.json
    voice: pt-BR-Wavenet-A

google_assistant:
  project_id: !secret google_project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  # exposed_domains:
  #   - light
  #   - sensor
  entity_config:
    light.led_cozinha:
      expose: true
      name: Kitchen Lights
    light.luz_do_coquero:
      expose: true
      name: Plant Light
    sensor.bedroom_temperature:
      expose: true
      name: Bedroom Temperature

logger:
  default: warning
  logs:
    # log level for HA core
    homeassistant.core: info

    # log level for MQTT integration
    homeassistant.components.mqtt: warning

    # log level for all python scripts
    homeassistant.components.python_script: warning

    # individual log level for this python script
    homeassistant.components.python_script.my_new_script.py: warning
    homeassistant.components.google_assistant: info
    homeassistant.components.calendar: critical
    homeassistant.components.wled: error
    homeassistant.components.bmp280.sensor: error

    homeassistant.components.device_tracker: error

    # log level for the `aiohttp` Python package
    aiohttp: error

    # log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal

    homeassistant.components.mysensors: warning
    mysensors: warning

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named ./themes
  
lovelace:

      
homeassistant:
  customize: !include customize.yaml

mobile_app:
esphome:

recorder:
  db_url: !secret mariadb_conn_string
  auto_purge: false
  purge_keep_days: 30
  commit_interval: 3
  exclude:
    domains:
      - automation
      - updater
      - calendar
      - camera
    entities:
      - sensor.goes_datetime
      - sensor.goes16c13
      - sensor.memory_use_percent
      - sensor.load_1m
      - sun.sun
      - sensor.cpu_temperature
    entity_globs:
      - sensor.nextcloud_*
      - sensor.plogger*

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_pass
  max_retries: 3
  default_measurement: state


# nextcloud:
#   url: https://xyz.duckdns.org/
#   username: !secret nextcloud_username
#   password: !secret nextcloud_pass

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# spotcast:
#   sp_dc: !secret spotcast_sp_dc
#   sp_key: !secret spotcast_sp_key

mqtt:
  username: !secret mqtt_username
  password: !secret mqtt_passwd
  broker: 192.168.0.34

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1-255
    consider_home: 00:08:00
    interval_seconds: 60
    scan_options: -F –host-timeout 5s
    exclude:
      - 192.168.0.1
      - 192.168.0.34
    new_device_defaults:
      track_new_devices: true
  - platform: bluetooth_tracker
  


rest_command:
  assistant_broadcast:
    url: http://192.168.0.34:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"wesley", "broadcast":true}'
    
  assistant_converse:
    url: http://192.168.0.34:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"wesley", "converse":true}'

  assistant_relay:
    url: http://192.168.0.34:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"wesley"}'

notify:
  - platform: clicksend
    name: ClickSend
    username: !secret my_email
    api_key: !secret clicksend_api_key
    recipient: !secret my_phone_number
  
  - platform: smtp
    name: HASS_MAIL
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret auto_email
    encryption: starttls
    username: !secret auto_email
    password: !secret auto_passwd
    recipient:
      - !secret my_email
    sender_name: My Home Assistant
  
  - platform: html5
    name: wgas_html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  
mysensors:
  gateways:
    - device: '127.0.0.1'
      persistence_file: '/config/mysensors.json'
      tcp_port: 5003
  version: '2.3'

camera:
  - platform: generic
    still_image_url: "{{ states('sensor.goes16c13') }}"
    limit_refetch_to_url_change: true
  - platform: generic
    still_image_url: "https://www.ipmetradar.com.br/ver-img.php?img=15120"
    scan_interval: 300
    
sensor:
  - platform: rest
    resource: http://satelite.cptec.inpe.br/collection/lista/5388
    name: GOES16C13
    json_attributes_path: "$.list.[0]"
    json_attributes:
      - fileDate
      - fileTime
      - description
    value_template: '{{ value_json["list"][0]["url"] }}'
    scan_interval: 300
  - platform: template
    sensors:
      goes_datetime:
        value_template: >-
          {% set goesDateTime = 
            state_attr('sensor.goes16c13','fileDate') + ' ' + state_attr('sensor.goes16c13','fileTime') 
          %}
          {{ ((as_timestamp(goesDateTime)|int ) - 3*3600) | timestamp_local }}
      goes_description:
        value_template: "{{ state_attr('sensor.goes16c13','description') }}"
  - platform: systemmonitor
    resources:
      - type: load_1m
      - type: memory_use_percent
  - platform: authenticated
  # - platform: mqtt
  #   unique_id: "coq_hum"
  #   name: "Coqueiro"
  #   state_topic: "varanda/sensors/soil_humidity"
  #   unit_of_measurement: 'u'  
    
  - platform: moon  

  - platform: command_line
    name: "CPU temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    
  - platform: openexchangerates
    api_key: !secret openexchangerates_api_key
    base: USD
    quote: EUR
  
  # - platform: aftership
  #   api_key: !secret aftership_api_key
  
  - platform: template
    sensors:
      euro:
        value_template: "{{ ((state_attr('sensor.exchange_rate_sensor', 'BRL') | float)/(states('sensor.exchange_rate_sensor') | float)) | round(3) }}"
        friendly_name: 'Cotação Euro'
        unit_of_measurement: 'BRL'
      dolar:
        value_template: "{{(state_attr('sensor.exchange_rate_sensor', 'BRL') | float) | round(3) }}"
        friendly_name: 'Cotação Dolar'
        unit_of_measurement: 'BRL'
      coq_sensor_power_delay:
        value_template: '{{ states.input_number.coq_sensor_power_delay.state | int }}'  
  
  - platform: bmp280
    name: "Bedroom"
    i2c_address: 0x77
  

light:
  - platform: mqtt
    name: Luz do Coquero
    unique_id: "luz_coqueiro"
    command_topic: 82_b/light/fastled_ws2811_light/command
    state_topic: 82_b/light/fastled_ws2811_light/state
    optimistic: true
    retain: true
    rgb: true
    brightness: true
    optimistic: true
    schema: json
    qos: 0

input_select:
  wled_presets:
    options:
      - "[PL=01] Preset 1"
      - "[PL=02] Preset 2"
      - "[PL=03] Preset 3"
      - "[PL=04] Preset 4"
      - "[PL=05] Preset 5"
      - "[PL=06] Preset 6"
      - "[PL=07] Preset 7"
      - "[PL=08] BlueSpark"
      - "[PL=09] Preset 9"
      - "[PL=10] Preset 10"
      - "[PL=11] Mari Preset"
      - "[PL=12] Preset 12"
      - "[PL=13] Preset 13"
      - "[PL=14] Full White"
      - "[PL=15] Preset 15"
      - "[PL=16] Preset 16"

  wled_palette_list:
    options:
      - "[FP=00] Default"
      - "[FP=01] Random Cycle"
      - "[FP=02] Primary color"
      - "[FP=03] Based on primary"
      - "[FP=04] Set colors"
      - "[FP=05] Based on set"
      - "[FP=06] Party"
      - "[FP=07] Cloud"
      - "[FP=08] Lava"
      - "[FP=09] Ocean"
      - "[FP=10] Forest"
      - "[FP=11] Rainbow"
      - "[FP=12] Rainbow bands"
      - "[FP=13] Sunset"
      - "[FP=14] Rivendell"
      - "[FP=15] Breeze"
      - "[FP=16] Red & Blue"
      - "[FP=17] Yellowout"
      - "[FP=18] Analoguous"
      - "[FP=19] Splash"
      - "[FP=20] Pastel"
      - "[FP=21] Sunset 2"
      - "[FP=22] Beech"
      - "[FP=23] Vintage"
      - "[FP=24] Departure"
      - "[FP=25] Landscape"
      - "[FP=26] Beach"
      - "[FP=27] Sherbet"
      - "[FP=28] Hult"
      - "[FP=29] Hult 64"
      - "[FP=30] Drywet"
      - "[FP=31] Jul"
      - "[FP=32] Grintage"
      - "[FP=33] Rewhi"
      - "[FP=34] Tertiary"
      - "[FP=35] Fire"
      - "[FP=36] Icefire"
      - "[FP=37] Cyane"
      - "[FP=38] Light Pink"
      - "[FP=39] Autumn"
      - "[FP=40] Magenta"
      - "[FP=41] Magred"
      - "[FP=42] Yelmag"
      - "[FP=43] Yelblu"
      - "[FP=44] Orange & Teal"
      - "[FP=45] Tiamat"
      - "[FP=46] April Night"
      - "[FP=47] Orangery"
      - "[FP=48] C9"
      - "[FP=49] Sakura"
      - "[FP=50] Aurora"

input_number:
  ledspeed:
    name: Speed
    initial: 0
    min: 0
    max: 255
    step: 1
  ledintensity:
    name: Intensity
    initial: 0
    min: 0
    max: 255
    step: 1


  
